package com.example.eis.ui.api

enum class ApiAction {
    LOGIN,
    GET_MOBILE_LIST,
    GET_MOBILE_GENERAL,
    ADD_MOBILE_GENERAL,
    ADD_MOBILE_VEHICLE,
    ADD_AREA_GENERAL,
    ADD_AREA_SOURCE,
    DELETE_MOBILE_VEHICLE,
    UPDATE_MOBILE_GENERAL
}