package com.example.eis.ui.api

enum class ApiAction {
    LOGIN,
    GET_MOBILE_LIST,
    GET_MOBILE_GENERAL,
    GET_AREA_LIST,
    GET_AREA_GENERAL,
    GET_STATIONARY_LIST,
    GET_STATIONARY_GENERAL,
    ADD_MOBILE_GENERAL,
    ADD_MOBILE_VEHICLE,
    ADD_AREA_GENERAL,
    ADD_AREA_SOURCE,
    ADD_STATIONARY_GENERAL,
    ADD_STATIONARY_PLANT,
    ADD_PLANT_APSI,
    DELETE_MOBILE_VEHICLE,
    DELETE_AREA_SOURCE,
    DELETE_STATIONARY_PLANT,
    DELETE_PLANT_APSI,
    UPDATE_MOBILE_GENERAL,
    UPDATE_AREA_GENERAL,
    UPDATE_STATIONARY_GENERAL
}